export const PERFORMANCE_THRESHOLDS = {
  LOW_FPS_THRESHOLD: 40,
  TARGET_FPS: 60,
  FRAME_DROP_LIMIT: 10,
  LOW_FPS_COUNT_LIMIT: 5,
}

export const TEST_CONFIG = {
  COUNTDOWN_DURATION: 3,
  DEFAULT_CAMERA_POSITION: [0, 0, 30],
  DEFAULT_FOV: 75,
}
